"""init

Revision ID: 2b2e26e7e3d5
Revises: 
Create Date: 2026-03-26 17:16:41.806767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b2e26e7e3d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('supplier_offer_id', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('adt', sa.Numeric(), nullable=False),
    sa.Column('chd', sa.Numeric(), nullable=False),
    sa.Column('inf', sa.Numeric(), nullable=False),
    sa.Column('ins', sa.Numeric(), nullable=False),
    sa.Column('class_', sa.String(length=2), nullable=True),
    sa.Column('direct', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_active_true', 'offers', ['origin', 'destination', 'departure_date', 'price'], unique=False, postgresql_where=sa.text('is_active IS true'))
    op.create_index('idx_search', 'offers', ['origin', 'destination', 'departure_date', 'price'], unique=False)
    op.create_index('ux_offer', 'offers', ['provider_id', 'supplier_offer_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('admin', 'agent', name='userrole'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ux_offer', table_name='offers')
    op.drop_index('idx_search', table_name='offers')
    op.drop_index('idx_active_true', table_name='offers', postgresql_where=sa.text('is_active IS true'))
    op.drop_table('offers')
    # ### end Alembic commands ###
